### ISSUE TITLE
Major Issue with HMR

### ISSUE THREAD

**Issue by rezaerami** [MostafaRastegar/es6-simple-carousel#8]
there is a major issue with Hot Module Reloading for the slider.
each time that slider makes a new instance, it keeps the old one.
so the arrows and dots would be appended instead of being overwritten.
check this out one code sandbox:
https://codesandbox.io/s/vigorous-visvesvaraya-o8hv0

for now, I fixed it by adding a flag to check if slider should be initialized or not
remove SimpleCarousel line 16 --> setSliderInitialized(true);
to reproduce the issue

**Comment by MostafaRastegar** [comment]
Fix on v1.1.0
